---
instance-id: ${instance_id}
local-hostname: ${hostname}
network:
  version: 2
  ethernets:
    ens33:
      dhcp4: false
      addresses:
        - ${ip_address}${subnet}
      gateway4: ${gateway}
      nameservers:
        addresses:
          - ${join("\n          - ", nameservers)}
